### ISSUE TITLE
front not font in dotfiles/.config/compton.conf

### ISSUE THREAD

**Issue by kingy9000** [leofa/dotfiles#1]
Hey, I was looking at your compton.conf from a [reddit thread about i3 4.12 release](https://www.reddit.com/r/i3wm/comments/4922yl/i3_412_whats_new/).

I noticed that you have an incorrect setting:
`glx-copy-from-font = true` it should instead be `glx-copy-from-front = true`
Notice the difference between font and f**r**ont.

You can refer to the compton man page to see that there is no reference to the setting glx-copy-from-font but there is to glx-copy-from-f**r**ont.

Please let me know if I am wrong but as I failed to find any reference to the font setting I am assuming it's a minor typo in the setting.

**Comment by leofa** [comment]
wow thnx didn't notice it, apparently compton let's me run it with a typo and not crap out, thanks for pointing that out,  just fixed it

**Comment by leofa** [comment]
glx-copy-from-front does not play nice on intel integrated gfx so disabled it https://github.com/leofa/dotfiles/commit/98459ee5fa95a4c17d2a19c03dcfec31299cd7ef
closing this issue now

**Comment by kingy9000** [comment]
Ah yes, sorry should have mentioned that `glx-copy-from-front` tends to not work well on opensource drivers. Good to see that you figured it out yourself.
